### ISSUE TITLE
在 v3.0.0 无法使用插件，需要适配

### ISSUE THREAD

**Issue by TCOTC** [TechDecryptor/pot-app-translate-plugin-youdao#2]
https://github.com/pot-app/pot-desktop/issues/848#issuecomment-2185040654

模板仓库：https://github.com/pot-app/pot-app-translate-plugin-template

**Comment by Natural-selection1** [comment]
同样的问题

**Comment by TechDecryptor** [comment]
https://github.com/TechDecryptor/pot-app-translate-plugin-youdao/releases/tag/2.0.0

**Comment by elarbor** [comment]
能不能开通 GitHub Discussion 啊
