### ISSUE TITLE
potext文件在哪里？？为什么找不到，到底要咋安装呢？有没有大佬指点一下

### ISSUE THREAD

**Issue by Panda-Z-Coding** [TechDecryptor/pot-app-translate-plugin-youdao#3]

**Comment by TechDecryptor** [comment]
https://github.com/TechDecryptor/pot-app-translate-plugin-youdao/releases/tag/2.0.0

**Comment by elarbor** [comment]
@TechDecryptor https://github.com/TechDecryptor/pot-app-translate-plugin-youdao/releases
![image](https://github.com/user-attachments/assets/e6252ce5-a025-4c27-9b46-5174c747fe8f)
